# Change these first
owner: effect-digital # Your GitHub organization or username, where this repository lives
repo: wol-olympus-status # The name of this repository

sites:
  # Internal Systems
  - name: Olympus
    url: https://api.olympustech.ai/up
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/logo.svg
  - name: Marketing
    url: https://everest.wayoflife.com/up
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/logo.svg
  - name: Customer & Property Management
    url: https://portal.wayoflife.com/up
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/logo.svg
  - name: Tenants API
    url: https://tenants.api.wayoflife.com/health
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/logo.svg
  - name: Internal Qube API
    url: https://qube.api.wayoflife.com/up
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/logo.svg
  - name: Qube Service
    url: https://2617-portals.qubeglobalcloud.com/qubews/?wsdl
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/qube.png

  # Frontend Sites
  - name: Multi Family
    url: https://www.wayoflife.com/
  - name: Students
    url: https://student.wayoflife.com/
  - name: The Eades
    url: https://theeades.com/
  - name: The Draper
    url: https://thedraper.com/
  - name: Single Family
    url: https://home.wayoflife.com/
    icon: https://home.wayoflife.com/favicon.ico

    # Third-party services
  - name: Rightmove
    url: https://adfapi.rightmove.co.uk/
    icon: https://media.rightmove.co.uk/assets/shared-assets/favicons/light/favicon.ico
    expectedStatusCodes:
      - 403
      - 200
  - name: Netlify
    url: https://www.netlifystatus.com/api/v2/status.json
    __dangerous__body_degraded: '"indicator":"minor"'
    __dangerous__body_down: '"indicator":"(major|critical)"'
  - name: Cloudflare
    url: https://www.cloudflarestatus.com/api/v2/status.json
    __dangerous__body_degraded: '"indicator":"minor"'
    __dangerous__body_down: '"indicator":"(major|critical)"'
  - name: Storyblok
    url: https://api.storyblok.com/v2/cdn/spaces/me
    icon: https://www.storyblok.com/favicon.svg
    expectedStatusCodes:
      - 401

status-website:
  cname: status.olympustech.ai
  baseUrl: /
  apiBaseUrl: https://api.github.com
  themeUrl: https://status.olympustech.ai/theme.css
  logoUrl: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/logo.svg
  faviconSvg: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/main/assets/icon.svg
  name: Olympus Status
  introTitle: "**Olympus** System Status"
  introMessage: Real-time monitoring for Olympus platforms and services. This page provides live uptime data and incident history across all our systems, sites, and third-party integrations.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

