# Change these first
owner: effect-digital # Your GitHub organization or username, where this repository lives
repo: wol-olympus-status # The name of this repository

sites:
  # Systems
  - name: Olympus
    url: https://api.olympustech.ai/up
    icon: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/master/assets/logo.svg
  - name: Everest
    url: https://everest.wayoflife.com/up
  - name: Portal
    url: https://portal.wayoflife.com/up
  - name: Tenants API
    url: https://tenants.api.wayoflife.com/health
  - name: Qube
    url: https://qube.api.wayoflife.com/up
    icon: https://www.wayoflife.com/favicon.ico
  - name: Qube Service
    url: https://2617-portals.qubeglobalcloud.com/qubews/?wsdl
    icon: https://www.wayoflife.com/favicon.ico

  # Sites
  - name: Way of Life
    url: https://www.wayoflife.com/
  - name: Students
    url: https://student.wayoflife.com/
  - name: The Eades
    url: https://theeades.com/
  - name: The Draper
    url: https://thedraper.com/
  - name: Single Family
    url: https://home.wayoflife.com/
    icon: https://www.wayoflife.com/favicon.ico

    # Third-party services
    expectedStatusCodes:
      - 200
  - name: Rightmove
    url: https://adfapi.rightmove.co.uk/
    expectedStatusCodes:
      - 403
      - 200
  - name: Netlify Status
    url: https://www.netlifystatus.com/api/v2/status.json
    __dangerous__body_down: '"indicator":"(?!none)'
  - name: Cloudflare
    url: https://www.cloudflarestatus.com/api/v2/status.json
    __dangerous__body_down: '"indicator":"(?!none)'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /wol-olympus-status
  apiBaseUrl: https://api.github.com
  themeUrl: https://effect-digital.github.io/wol-olympus-status/theme.css
  logoUrl: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/master/assets/logo.svg
  faviconSvg: https://raw.githubusercontent.com/effect-digital/wol-olympus-status/master/assets/icon.svg
  name: Way of Life Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

